set (CMAKE_SYSTEM_NAME Linux)
set (CMAKE_SYSTEM_VERSION 1)

set (TOOLCHAIN "/opt/gcc-10.2.0")
set (COMPILER_PREFIX "${TOOLCHAIN}/bin/")
set (CMAKE_C_COMPILER "${COMPILER_PREFIX}gcc")
set (CMAKE_CXX_COMPILER "${COMPILER_PREFIX}g++")